### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by mak448a** [JJTech0130/ValidationRelay#4]
I tried signing into beeper mini https://mini.beeper.com/Beeper_Mini_v1.2.58.apk and entered in my registration code. It got stuck at the sign in page though, with this error:
![image](https://github.com/JJTech0130/ValidationRelay/assets/94062293/963e31f0-5331-4956-9429-073c218ca93d)

**Comment by JJTech0130** [comment]
Nothing that ValidationRelay can do about that, it simply forwards"validation data" from the iPhone to the app. Since Beeper Mini is not maintained, some problems have cropped up especially with the Apple ID sign-in process and its method of receiving the SMS verification. I would ask in the pypush or Beeper Discords, they might be able to point you towards a solution, maybe OpenBubbles would fulfill your needs?

**Comment by mak448a** [comment]
It's just to send messages from my computer, which I don't absolutely need. I also don't own a Mac, only a vm.

**Comment by mak448a** [comment]
It's just to send messages from my computer. I don't have a mac mini, so I guess I'll just stick with my phone for texting.

**Comment by JJTech0130** [comment]
OpenBubbles (different from BlueBubbles) should be able to function without a Mac, it can use a code from ValidationRelay just like Beeper Mini iirc?

**Comment by mak448a** [comment]
Oh it does! Ok, I'll use that. Thanks!

**Comment by mak448a** [comment]
It keeps saying "Failed" though.

**Comment by mak448a** [comment]
Sorry to keep bothering you, but I got in and now it doesn't work. Every text I try to send to an imessage person, it selects the text preset. And I can't change it either.
